# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Code Quality

on:
  push:
    branches: [ $DEFAULT_BRANCH ]
  pull_request:
    branches: [ $DEFAULT_BRANCH ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.15.0]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '18.x'
    - run: npm ci
    - run: npm run lint
    - run: npm test